<a href="https://colab.research.google.com/github/DatadevWil/Estudo/blob/main/Qui_Quadrado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.stats import chi2_contingency

In [2]:
#criação da matriz
#criando a matriz colocando as informações sobre a quantidade de homens e mulheres que assistem e que não assistem novela
novela = np.array([[19,6],[43,32]])
novela

array([[19,  6],
       [43, 32]])

In [3]:
# O segundo valor é o pvalue
# O valor de p é maior que 0,05 sendo assim não há diferença significativa
chi2_contingency(novela)

(2.037351443123939, 0.15347667161786666, 1, array([[15.5,  9.5],
        [46.5, 28.5]]))

In [9]:
#Criação de outra matriz para testar novamente a hipótese nula
novela2 = np.array([[88,12],[12,11]])
novela2

array([[88, 12],
       [12, 11]])

In [10]:
chi2_contingency(novela2)
# com o resultado obtido que é bem menor que 0,05 podemos concluir que a proporção de homens que assistem novela é maior que a de mulheres

(13.518519612476371,
 0.00023622068488039015,
 1,
 array([[81.30081301, 18.69918699],
        [18.69918699,  4.30081301]]))